# Generated by Django 3.0.8 on 2020-07-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_profile_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="githubusername",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
