# Generated by Django 3.0.8 on 2020-07-30 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_githubusername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='githubusername',
            new_name='githuburl',
        ),
    ]
