# Generated by Django 3.0.8 on 2020-07-30 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200731_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='githuburl',
            new_name='githubusername',
        ),
    ]
