# Generated by Django 3.0.8 on 2020-08-02 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_auto_20200731_0021"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="points",
            new_name="domes",
        ),
    ]
