# Generated by Django 3.1 on 2020-08-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_auto_20200805_2110"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="githubusername",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
