# Generated by Django 3.0.8 on 2020-07-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_query_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
