# Generated by Django 3.0.8 on 2020-07-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0003_answer_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="query",
            name="category",
            field=models.CharField(
                choices=[
                    ("GEN", "General Development"),
                    ("WEB", "Web Development"),
                    ("CS", "Computer Science"),
                    ("CAS", "Casual Development"),
                ],
                default="GEN",
                max_length=3,
            ),
        ),
    ]
