# Generated by Django 3.0.8 on 2020-08-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20200725_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='isaccepted',
            field=models.BooleanField(default=False),
        ),
    ]
