# Generated by Django 3.0.8 on 2020-08-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0008_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
