# Generated by Django 3.1 on 2020-08-17 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("creator", "0002_auto_20200813_1239"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="readmedevs",
            new_name="readme_devs",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="readmeusers",
            new_name="readme_users",
        ),
    ]
