# Generated by Django 3.1 on 2020-08-17 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("creator", "0003_auto_20200817_1334"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="readme_devs",
            new_name="documentation_Devs",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="readme_users",
            new_name="documentation_Users",
        ),
    ]
