# Generated by Django 3.1 on 2020-08-17 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creator", "0004_auto_20200817_1338"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="additional_File",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="media",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "pptx",
                            "ppt",
                            "md",
                            "txt",
                            "jpeg",
                            "png",
                        ]
                    )
                ],
            ),
        ),
    ]
