# Generated by Django 3.1 on 2020-08-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0005_product_additional_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='github_repo',
            new_name='github_Repo_Link',
        ),
    ]
