# Generated by Django 3.1 on 2020-08-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0006_auto_20200802_1652"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ques",
            name="slug",
            field=models.SlugField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="slug",
            field=models.SlugField(max_length=256, null=True, unique=True),
        ),
    ]
