# Generated by Django 3.0.8 on 2020-07-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coder", "0003_auto_20200725_1936"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="iscorrect",
        ),
    ]
