# Generated by Django 3.0.8 on 2020-07-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0004_remove_question_iscorrect'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='iscorrect',
            field=models.BooleanField(default=False),
        ),
    ]
