# Generated by Django 3.0.8 on 2020-07-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0006_remove_question_iscorrect'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='typeof',
            field=models.CharField(choices=[('JAVA', 'Java'), ('PYTHON', 'Python'), ('RUST', 'Rust'), ('C++', 'C++')], default='PYTHON', max_length=10),
        ),
    ]
