# Generated by Django 3.1 on 2020-08-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coder", "0012_auto_20200822_2009"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="language",
            field=models.CharField(
                choices=[
                    ("JAVA", "Java"),
                    ("PYTHON", "Python"),
                    ("RUST", "Rust"),
                    ("C++", "C++"),
                    ("General", "General"),
                ],
                default="PYTHON",
                max_length=10,
            ),
        ),
    ]
