# Generated by Django 3.1 on 2020-08-23 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coder", "0016_auto_20200823_1210"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="language",
            field=models.CharField(
                choices=[
                    ("JAVA", "Java"),
                    ("PYTHON", "Python"),
                    ("RUST", "Rust"),
                    ("C++", "C++"),
                    ("GO", "Go"),
                    ("C", "C"),
                ],
                default="PYTHON",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="result",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="media",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "txt",
                            "py",
                            "java",
                            "cpp",
                            "c++",
                            "rs",
                            "go",
                            "c",
                        ])
                ],
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="typeof",
            field=models.CharField(
                choices=[
                    ("JAVA", "Java"),
                    ("PYTHON", "Python"),
                    ("RUST", "Rust"),
                    ("C++", "C++"),
                    ("GO", "Go"),
                    ("C", "C"),
                    ("General", "General"),
                ],
                default="PYTHON",
                max_length=10,
            ),
        ),
    ]
