# Generated by Django 3.0.8 on 2020-07-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="serialno",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
