# Generated by Django 3.0.8 on 2020-07-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0002_resource_serialno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="quizlink",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
