# Generated by Django 3.0.8 on 2020-07-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0003_auto_20200727_0345"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="quizlink",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
