# Generated by Django 3.1 on 2020-08-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0004_auto_20200727_2300"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="slug",
            field=models.SlugField(max_length=256, null=True, unique=True),
        ),
    ]
