# Generated by Django 3.1 on 2020-08-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0009_auto_20200809_2224"),
    ]

    operations = [
        migrations.AddField(
            model_name="progress",
            name="slug",
            field=models.SlugField(max_length=256, null=True, unique=True),
        ),
    ]
